# java
package Practice;
import java.io.*;
public class Exception22 {
	public static void main(String[] args)
	{
		try 
		{
			method1();
		}
		catch(Exception e) 
		{
			System.out.println("main메서드에서 예외처리가 되었습니다.");
		}
	}
	
	static void method1() throws Exception
	{
		try 
		{
			throw new Exception();
		}
		catch(Exception e) 
		{
			System.out.println("method1메서드에서 예외처리");
			throw e; // 다시 예외발생시키기 
		}
	}
}
